import type { GenerateResponse } from "@/types/test-case";

export const demoPrdHighlights = [
  "用户可通过手机号验证码或密码登录，支持新用户注册与账号锁定提示。",
  "首页展示会员任务列表，任务按状态、类型、奖励排序，并支持空状态和失败重试。",
  "用户可领取任务、完成任务、查看进度，系统需要处理重复提交和过期任务。",
  "任务完成后发放积分或优惠券，奖励需要防重复发放并支持异常补偿。",
  "不同会员等级展示不同权益，风控命中时限制领取高价值奖励。",
];

export const demoGenerateResponse: GenerateResponse = {
  source: "demo",
  fileName: "示例PRD-会员任务中心.pdf",
  summary:
    "内嵌演示案例：基于一份“会员任务中心”示例 PRD，按账号登录、任务列表、任务领取与进度、奖励结算、会员权益与风控 5 个模块展示 36 条测试用例。功能类用例占多数，并包含正向、逆向、重复操作、中断、状态不满足、权限不足、边界和性能场景，适合快速体验模块筛选、类型筛选、搜索与导出。",
  warnings: [],
  cases: [
    {
      id: "TC-DEMO-001",
      category: "功能",
      priority: "P0",
      module: "账号登录与注册",
      title: "已注册用户使用正确手机号和密码登录成功",
      preconditions: "用户账号已注册且状态正常，网络连接正常。",
      steps: ["打开登录页", "输入已注册手机号", "输入正确密码", "点击登录"],
      expectedResult: "系统登录成功，进入任务中心首页，并正确展示用户昵称、会员等级和任务入口。",
    },
    {
      id: "TC-DEMO-002",
      category: "功能",
      priority: "P0",
      module: "账号登录与注册",
      title: "密码错误时登录失败并给出明确提示",
      preconditions: "用户账号已注册且状态正常。",
      steps: ["打开登录页", "输入已注册手机号", "输入错误密码", "点击登录"],
      expectedResult: "系统拒绝登录，提示密码错误，不创建登录态，不进入任务中心。",
    },
    {
      id: "TC-DEMO-003",
      category: "功能",
      priority: "P0",
      module: "账号登录与注册",
      title: "未注册手机号尝试登录时引导注册",
      preconditions: "手机号未注册，验证码服务可用。",
      steps: ["打开登录页", "输入未注册手机号", "输入任意密码或验证码", "点击登录"],
      expectedResult: "系统提示账号未注册，并提供注册入口，不应误创建已有账号登录态。",
    },
    {
      id: "TC-DEMO-004",
      category: "功能",
      priority: "P1",
      module: "账号登录与注册",
      title: "验证码注册成功后自动进入任务中心",
      preconditions: "手机号未注册，验证码发送和校验服务正常。",
      steps: ["进入注册页", "输入合法手机号", "获取并输入正确验证码", "勾选协议后提交注册"],
      expectedResult: "系统创建账号并自动登录，任务中心展示新用户任务和默认会员等级。",
    },
    {
      id: "TC-DEMO-005",
      category: "功能",
      priority: "P1",
      module: "账号登录与注册",
      title: "用户未勾选协议时注册提交失败",
      preconditions: "用户位于注册页，手机号和验证码均合法。",
      steps: ["输入合法手机号", "输入正确验证码", "不勾选用户协议", "点击注册"],
      expectedResult: "系统阻止注册提交，提示需同意协议，不创建用户账号。",
    },
    {
      id: "TC-DEMO-006",
      category: "功能",
      priority: "P1",
      module: "账号登录与注册",
      title: "重复点击登录按钮只发起一次登录请求",
      preconditions: "用户账号正常，登录接口响应存在短暂延迟。",
      steps: ["输入正确手机号和密码", "连续快速点击登录按钮多次", "等待接口返回"],
      expectedResult: "页面进入提交中状态，仅产生一次有效登录请求，最终登录结果只处理一次。",
    },
    {
      id: "TC-DEMO-007",
      category: "异常",
      priority: "P1",
      module: "账号登录与注册",
      title: "登录接口超时时展示重试入口",
      preconditions: "登录接口超时或网关返回超时错误。",
      steps: ["输入正确登录信息", "点击登录", "等待接口超时"],
      expectedResult: "系统停留在登录页，提示网络异常或服务超时，并提供可再次点击的登录按钮。",
    },
    {
      id: "TC-DEMO-008",
      category: "权限",
      priority: "P0",
      module: "账号登录与注册",
      title: "账号锁定用户登录时禁止进入任务中心",
      preconditions: "用户账号因安全策略被锁定。",
      steps: ["输入被锁定账号手机号", "输入正确密码", "点击登录"],
      expectedResult: "系统拒绝登录，提示账号已锁定或需申诉，不返回任务中心访问令牌。",
    },
    {
      id: "TC-DEMO-009",
      category: "功能",
      priority: "P0",
      module: "任务列表与筛选",
      title: "任务中心默认展示可领取任务并按优先级排序",
      preconditions: "用户已登录，存在多个可领取任务。",
      steps: ["进入任务中心首页", "查看任务列表", "检查任务排序和卡片内容"],
      expectedResult: "列表展示任务名称、奖励、截止时间和状态，推荐任务优先展示，排序符合 PRD 规则。",
    },
    {
      id: "TC-DEMO-010",
      category: "功能",
      priority: "P1",
      module: "任务列表与筛选",
      title: "按任务类型筛选后仅展示匹配任务",
      preconditions: "用户已登录，任务列表包含签到、浏览、购买等多种类型。",
      steps: ["进入任务中心", "选择任务类型筛选项", "切换不同类型"],
      expectedResult: "系统仅展示当前类型任务，任务数量和空状态随筛选条件实时更新。",
    },
    {
      id: "TC-DEMO-011",
      category: "功能",
      priority: "P1",
      module: "任务列表与筛选",
      title: "无匹配任务时展示空状态和清除筛选入口",
      preconditions: "当前筛选条件下没有任务。",
      steps: ["进入任务中心", "选择无任务的筛选条件", "观察列表区域"],
      expectedResult: "系统展示空状态文案和清除筛选入口，不展示上一轮筛选残留任务。",
    },
    {
      id: "TC-DEMO-012",
      category: "功能",
      priority: "P1",
      module: "任务列表与筛选",
      title: "任务列表刷新后保留当前筛选条件",
      preconditions: "用户已选择任务类型筛选项。",
      steps: ["在任务中心选择筛选条件", "下拉刷新或点击刷新", "查看刷新后的列表"],
      expectedResult: "刷新完成后仍使用当前筛选条件，列表数据更新但筛选状态不丢失。",
    },
    {
      id: "TC-DEMO-013",
      category: "边界",
      priority: "P2",
      module: "任务列表与筛选",
      title: "任务标题超长时卡片布局不被撑破",
      preconditions: "存在标题长度超过 40 个中文字符的任务。",
      steps: ["进入任务中心", "查看超长标题任务卡片", "切换不同屏幕宽度"],
      expectedResult: "标题按设计换行或省略，奖励和按钮仍可见，不遮挡其他内容。",
    },
    {
      id: "TC-DEMO-014",
      category: "异常",
      priority: "P1",
      module: "任务列表与筛选",
      title: "任务列表接口失败时展示失败状态",
      preconditions: "任务列表接口返回 5xx 或业务失败码。",
      steps: ["进入任务中心", "触发任务列表加载失败", "点击重试"],
      expectedResult: "系统展示加载失败提示和重试入口，重试成功后恢复正常列表。",
    },
    {
      id: "TC-DEMO-015",
      category: "性能",
      priority: "P2",
      module: "任务列表与筛选",
      title: "大量任务分页加载时页面保持可操作",
      preconditions: "用户存在 200 条以上历史任务，接口支持分页。",
      steps: ["进入任务中心", "连续滚动加载多页任务", "观察列表滚动和筛选响应"],
      expectedResult: "页面无明显卡顿，分页请求按需触发，重复数据不被追加。",
    },
    {
      id: "TC-DEMO-016",
      category: "功能",
      priority: "P0",
      module: "任务领取与进度",
      title: "用户领取可领取任务成功",
      preconditions: "用户已登录，任务状态为可领取，库存和有效期正常。",
      steps: ["进入任务详情", "点击领取任务", "返回任务列表"],
      expectedResult: "任务状态更新为进行中，列表和详情页状态一致，并展示进度入口。",
    },
    {
      id: "TC-DEMO-017",
      category: "功能",
      priority: "P0",
      module: "任务领取与进度",
      title: "已领取任务再次领取时不重复创建任务实例",
      preconditions: "用户已经领取该任务，任务仍在进行中。",
      steps: ["进入已领取任务详情", "再次点击领取或刷新后重复点击领取", "查看任务状态"],
      expectedResult: "系统提示任务已领取，不创建重复实例，进度和奖励记录保持唯一。",
    },
    {
      id: "TC-DEMO-018",
      category: "功能",
      priority: "P0",
      module: "任务领取与进度",
      title: "任务完成后进度变为 100% 并进入待领奖状态",
      preconditions: "用户已领取任务，任务完成条件已满足。",
      steps: ["完成任务要求的业务动作", "返回任务详情", "查看任务进度"],
      expectedResult: "任务进度更新为 100%，状态变为待领奖或已完成，展示领取奖励入口。",
    },
    {
      id: "TC-DEMO-019",
      category: "功能",
      priority: "P1",
      module: "任务领取与进度",
      title: "未满足完成条件时提交完成失败",
      preconditions: "用户已领取任务，但实际完成次数未达到要求。",
      steps: ["进入任务详情", "点击完成或领取奖励", "查看系统校验结果"],
      expectedResult: "系统拒绝完成任务，提示还需完成的条件，不发放奖励。",
    },
    {
      id: "TC-DEMO-020",
      category: "功能",
      priority: "P1",
      module: "任务领取与进度",
      title: "任务过期后用户无法继续完成",
      preconditions: "用户已领取任务，当前时间晚于任务截止时间。",
      steps: ["进入过期任务详情", "尝试继续完成任务动作", "查看任务状态"],
      expectedResult: "系统提示任务已过期，任务状态更新为已失效，不允许继续领取奖励。",
    },
    {
      id: "TC-DEMO-021",
      category: "边界",
      priority: "P1",
      module: "任务领取与进度",
      title: "进度刚好达到完成阈值时判定成功",
      preconditions: "任务要求完成 3 次操作，用户当前已完成 2 次。",
      steps: ["完成第 3 次有效操作", "刷新任务详情", "查看进度和状态"],
      expectedResult: "系统准确判定达到完成阈值，进度显示 3/3 或 100%，不要求额外操作。",
    },
    {
      id: "TC-DEMO-022",
      category: "异常",
      priority: "P1",
      module: "任务领取与进度",
      title: "完成任务时进度同步失败可恢复",
      preconditions: "用户完成任务动作后，进度同步接口返回失败。",
      steps: ["完成任务动作", "触发进度同步失败", "重新进入任务详情或点击刷新"],
      expectedResult: "系统不错误发奖，提示同步中或可重试，后续同步成功后状态恢复正确。",
    },
    {
      id: "TC-DEMO-023",
      category: "性能",
      priority: "P2",
      module: "任务领取与进度",
      title: "任务进度频繁刷新时接口调用受控",
      preconditions: "用户在任务详情页频繁切换前后台或下拉刷新。",
      steps: ["进入任务详情", "连续触发多次刷新", "观察接口请求次数和页面响应"],
      expectedResult: "页面不会无限制并发请求，最后一次进度结果准确展示。",
    },
    {
      id: "TC-DEMO-024",
      category: "功能",
      priority: "P0",
      module: "奖励结算与发放",
      title: "完成任务后领取积分奖励成功",
      preconditions: "用户任务已完成，积分奖励库存充足。",
      steps: ["进入待领奖任务详情", "点击领取奖励", "查看积分余额"],
      expectedResult: "奖励领取成功，积分余额增加，任务状态变为已领奖，并生成奖励流水。",
    },
    {
      id: "TC-DEMO-025",
      category: "功能",
      priority: "P0",
      module: "奖励结算与发放",
      title: "重复点击领取奖励只发放一次",
      preconditions: "用户任务已完成，奖励接口响应存在延迟。",
      steps: ["点击领取奖励", "在加载中连续点击领取按钮", "查看奖励流水"],
      expectedResult: "系统只创建一条奖励流水，只增加一次积分或优惠券，按钮进入防重复提交状态。",
    },
    {
      id: "TC-DEMO-026",
      category: "功能",
      priority: "P1",
      module: "奖励结算与发放",
      title: "奖励库存不足时领取失败且任务状态不变",
      preconditions: "任务已完成，但奖励库存已耗尽。",
      steps: ["进入待领奖任务详情", "点击领取奖励", "查看任务状态和提示"],
      expectedResult: "系统提示奖励已领完或库存不足，不增加余额，任务保持待领奖或按 PRD 规则处理。",
    },
    {
      id: "TC-DEMO-027",
      category: "功能",
      priority: "P1",
      module: "奖励结算与发放",
      title: "优惠券奖励发放成功后可在券包查看",
      preconditions: "任务奖励类型为优惠券，用户已完成任务。",
      steps: ["领取优惠券奖励", "进入我的券包", "查看优惠券详情"],
      expectedResult: "券包出现对应优惠券，面额、有效期、使用门槛与任务配置一致。",
    },
    {
      id: "TC-DEMO-028",
      category: "边界",
      priority: "P1",
      module: "奖励结算与发放",
      title: "奖励金额为最小有效值时可正常发放",
      preconditions: "任务配置积分奖励为系统允许的最小正整数值。",
      steps: ["完成任务", "领取积分奖励", "查看积分流水"],
      expectedResult: "系统按最小值发放奖励，流水金额准确，不因金额过小被过滤。",
    },
    {
      id: "TC-DEMO-029",
      category: "异常",
      priority: "P0",
      module: "奖励结算与发放",
      title: "奖励发放成功但前端超时时可查询到最终结果",
      preconditions: "奖励服务已成功发放，但前端请求超时。",
      steps: ["点击领取奖励", "触发前端超时", "刷新任务详情和奖励流水"],
      expectedResult: "系统展示最终一致结果，不重复发放；用户可看到已领奖状态和奖励流水。",
    },
    {
      id: "TC-DEMO-030",
      category: "权限",
      priority: "P1",
      module: "奖励结算与发放",
      title: "未登录用户不能直接调用奖励领取接口",
      preconditions: "用户未登录或登录态已过期。",
      steps: ["直接访问奖励领取接口或点击领取入口", "观察系统响应"],
      expectedResult: "系统返回未授权并引导登录，不创建奖励流水。",
    },
    {
      id: "TC-DEMO-031",
      category: "功能",
      priority: "P1",
      module: "会员权益与风控",
      title: "不同会员等级展示对应可参与任务",
      preconditions: "系统存在普通会员和高级会员专属任务。",
      steps: ["分别使用普通会员和高级会员登录", "进入任务中心", "对比任务列表"],
      expectedResult: "普通会员看不到或不可领取高级任务，高级会员可看到并领取符合等级的任务。",
    },
    {
      id: "TC-DEMO-032",
      category: "功能",
      priority: "P1",
      module: "会员权益与风控",
      title: "会员等级提升后刷新任务权益",
      preconditions: "用户完成升级条件，会员等级从普通提升为高级。",
      steps: ["完成会员升级动作", "返回任务中心", "刷新任务列表"],
      expectedResult: "任务中心展示升级后的会员权益和新解锁任务，不需要重新登录即可生效。",
    },
    {
      id: "TC-DEMO-033",
      category: "功能",
      priority: "P0",
      module: "会员权益与风控",
      title: "风控命中用户领取高价值任务失败",
      preconditions: "用户被风控规则标记，高价值任务需要风控校验。",
      steps: ["进入高价值任务详情", "点击领取任务", "查看校验结果"],
      expectedResult: "系统拒绝领取并展示合规提示，不创建任务实例，不发放奖励。",
    },
    {
      id: "TC-DEMO-034",
      category: "边界",
      priority: "P2",
      module: "会员权益与风控",
      title: "会员等级刚达到门槛时可领取专属任务",
      preconditions: "任务要求会员等级大于等于 3，用户等级刚好为 3。",
      steps: ["使用等级为 3 的用户登录", "进入专属任务详情", "点击领取"],
      expectedResult: "系统允许领取任务，门槛判断包含等于边界。",
    },
    {
      id: "TC-DEMO-035",
      category: "权限",
      priority: "P0",
      module: "会员权益与风控",
      title: "普通会员不能通过篡改参数领取高级任务",
      preconditions: "普通会员已登录，高级任务 ID 可被构造。",
      steps: ["使用普通会员登录", "构造高级任务领取请求", "提交请求"],
      expectedResult: "服务端校验会员等级并拒绝请求，前端不应仅依赖按钮隐藏保护权限。",
    },
    {
      id: "TC-DEMO-036",
      category: "性能",
      priority: "P2",
      module: "会员权益与风控",
      title: "风控校验不应明显拖慢任务领取",
      preconditions: "风控服务正常，任务领取需要同步校验。",
      steps: ["连续领取多个需要风控校验的任务", "记录接口响应时间", "观察页面加载状态"],
      expectedResult: "领取请求在 PRD 约定时限内返回，页面有明确加载状态，超时后可重试。",
    },
  ],
};
